version: '3.4'

services:
  ntp-server:
    build: .
    image: cturra/ntp:latest
    restart: always
    privileged: true
    depends_on:
      - ntp-client
    read_only: true
    tmpfs:
      - /etc/chrony:rw,mode=1750
      - /run/chrony:rw,mode=1750
      - /var/lib/chrony:rw,mode=1750
    environment:
      - NTP_CLIENTS=ntp-client
      - LOG_LEVEL=0

  ntp-client:
    build: .
    image: cturra/ntp:latest
    restart: always
    privileged: true
    read_only: true
    tmpfs:
      - /etc/chrony:rw,mode=1750
      - /run/chrony:rw,mode=1750
      - /var/lib/chrony:rw,mode=1750
    environment:
      - NTP_SERVER=ntp-server
      - LOG_LEVEL=0
