#!/bin/sh

CHRONY_CONF_FILE="/etc/chrony/chrony.conf"

# confirm correct permissions on chrony run directory
if [ -d /run/chrony ]; then
  chown -R chrony:chrony /run/chrony
  chmod o-rx /run/chrony
  # remove previous pid file if it exist
  rm -f /var/run/chrony/chronyd.pid
fi

# confirm correct permissions on chrony variable state directory
if [ -d /var/lib/chrony ]; then
  chown -R chrony:chrony /var/lib/chrony
fi

## dynamically populate chrony config file.
{
  echo "# https://github.com/cturra/docker-ntp"
  echo
  echo "# chrony.conf file generated by startup script"
  echo "# located at /opt/startup.sh"
} > ${CHRONY_CONF_FILE}

# LOG_LEVEL environment variable is not present, so populate with chrony default (0)
# chrony log levels: 0 (informational), 1 (warning), 2 (non-fatal error) and 3 (fatal error)
if [ -z "${LOG_LEVEL}" ]; then
  LOG_LEVEL=0
else
  # confirm log level is between 0-3, since these are the only log levels supported
  if [ "${LOG_LEVEL}" -gt 3 ]; then
    # level outside of supported range, let's set to default (0)
    LOG_LEVEL=0
  fi
fi

if [ ! -z "${NTP_CLIENTS}" ]; then
  {
    echo
    echo "# local clients provided by NTP_CLIENTS environment variables."
    echo
    echo -n "initstepslew 1 " >> ${CHRONY_CONF_FILE}
  } >> ${CHRONY_CONF_FILE}

  IFS=","
  for N in $NTP_CLIENTS; do
    # strip any quotes found before or after ntp server
    echo -n ""${N//\"}" " >> ${CHRONY_CONF_FILE}
  done

  # final bits for the config file
  {
    echo
    echo "driftfile /var/lib/chrony/chrony.drift"
    echo "local stratum 8"
    echo "manual"
    echo "allow all"
    echo "smoothtime 400 0.01"
    echo "rtcsync"
    echo
  } >> ${CHRONY_CONF_FILE}
else
  {
    echo
    echo "# server provided by NTP_SERVER environment variables."
    echo
    echo "server ${NTP_SERVER} iburst"
    echo "driftfile /var/lib/chrony/chrony.drift"
    echo "allow all"
    echo "makestep 1.0 3"
    echo "rtcsync"
    echo
  } >> ${CHRONY_CONF_FILE}
fi

## startup chronyd in the foreground
cat ${CHRONY_CONF_FILE}
exec /usr/sbin/chronyd -u chrony -d -x -L ${LOG_LEVEL}
